version: '3.8'
services:
 php:
    build: .
    hostname: php
    privileged: false
 nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    hostname: nginx-cache
    privileged: false
    ports:
      - "5000:80"
    depends_on:
      - php
